import { NextRequest, NextResponse } from "next/server";
import { verifyDownloadToken } from "@/lib/download";

/**
 * GET /api/download/apk
 *
 * Serves the APK file if the signed download token is valid.
 * The token is generated by /api/download and expires after 1 hour.
 *
 * In production, this would redirect to a CDN or pre-signed S3 URL.
 * For MVP, it returns a placeholder response since the APK is not
 * yet built for distribution.
 */
export async function GET(request: NextRequest) {
  const { searchParams } = request.nextUrl;
  const token = searchParams.get("token");
  const expiresStr = searchParams.get("expires");
  const userId = searchParams.get("userId");

  if (!token || !expiresStr || !userId) {
    return NextResponse.json(
      { error: "Missing required parameters" },
      { status: 400 },
    );
  }

  const expires = parseInt(expiresStr, 10);
  if (isNaN(expires)) {
    return NextResponse.json(
      { error: "Invalid expiry" },
      { status: 400 },
    );
  }

  const isValid = verifyDownloadToken(userId, token, expires);
  if (!isValid) {
    return NextResponse.json(
      { error: "El enlace de descarga ha expirado o es inv\u00e1lido. Genera uno nuevo desde tu p\u00e1gina de descarga." },
      { status: 403 },
    );
  }

  // MVP: Return a placeholder since the APK is not yet built.
  // In production, replace this with:
  //   - A redirect to a CDN URL: return NextResponse.redirect(cdnUrl)
  //   - Or stream the file: return new NextResponse(fileStream, { headers })
  return NextResponse.json({
    message: "Download token verified. APK delivery endpoint ready.",
    note: "The APK file will be served here once the production build is available.",
    userId,
    validUntil: new Date(expires * 1000).toISOString(),
  });
}
